### ISSUE TITLE
Catch robot not work on first run error.

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#20]

**Comment by Robadob** [comment]
I've attempted to test this (it's been committed to the repo), but even when running software directly after Bluetooth connection I've been able to trigger the first run error.

Not sure whether to hold next release till this can be tested.

**Comment by Robadob** [comment]
Managed to get it to occur directly after rebooting robot.
This happened

```
U:\Archive2>java Test
EV3 found on ip: 10.0.1.1
Failed to connect to EV3: 1/5 attempts.
Retrying in 5 seconds.
EV3 found on ip: 10.0.1.1
Failed to connect to EV3: 2/5 attempts.
Retrying in 5 seconds.
EV3 found on ip: 10.0.1.1
Failed to connect to EV3: 3/5 attempts.
Retrying in 5 seconds.
EV3 found on ip: 10.0.1.1
Exception in thread "main" Exception in thread "Thread-2" lejos.hardware.port.PortException: java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is:
        java.net.SocketException: Software caused connection abort: recv failed
        at lejos.remote.ev3.RemoteKeys.waitForAnyEvent(RemoteKeys.java:35)
        at lejos.remote.ev3.RemoteKeys$KeysListenThread.run(RemoteKeys.java:155)

Caused by: java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is:
        java.net.SocketException: Software caused connection abort: recv failed
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:229)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
        at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194)
        at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148)
        at com.sun.proxy.$Proxy1.waitForAnyEvent(Unknown Source)
        at lejos.remote.ev3.RemoteKeys.waitForAnyEvent(RemoteKeys.java:33)
        ... 1 more
Caused by: java.net.SocketException: Software caused connection abort: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:215)
        ... 6 more
lejos.hardware.port.PortException: java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is:
        java.net.SocketException: Software caused connection abort: recv failed
        at lejos.remote.ev3.RemoteUARTPort.open(RemoteUARTPort.java:21)
        at lejos.remote.ev3.RemotePort.open(RemotePort.java:70)
        at lejos.hardware.sensor.UARTSensor.<init>(UARTSensor.java:57)
        at lejos.hardware.sensor.UARTSensor.<init>(UARTSensor.java:34)
        at lejos.hardware.sensor.EV3GyroSensor.<init>(EV3GyroSensor.java:68)
        at ShefRobot.Sensor.<init>(Sensor.java:67)
        at ShefRobot.GyroSensor.<init>(GyroSensor.java:25)
        at ShefRobot.Robot.getGyroSensor(Robot.java:253)
        at Test.main(Test.java:10)
Caused by: java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is:
        java.net.SocketException: Software caused connection abort: recv failed
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:229)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
        at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194)
        at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148)
        at com.sun.proxy.$Proxy0.openUARTPort(Unknown Source)
        at lejos.remote.ev3.RemoteUARTPort.open(RemoteUARTPort.java:19)
        ... 8 more
Caused by: java.net.SocketException: Software caused connection abort: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:215)
        ... 13 more
```

Not sure whether that's an error we can even catch, it doesn't appear to be part of our main stack.
